sudo: required
services:
  - docker

before_install:
  - docker build -t vineeshva/docker-react -f Dockerfile.dev .

script:
  - docker run vineeshva/docker-react npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-521758267958"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: 
      secure: "AKIAIE6OLJEJGTB2DJGQ"
    secret_access_key: 
      secure: "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"